php56.extensions.fileinfo: fix build with Clang 21
Fixes:

    error: a type specifier is required for all declarations

Picked out of https://github.com/php/php-src/commit/2181ed2e2ab0c137d843e2ebea1d7d92e7d9b759

Allows us to get rid of compile flag introduced in ce540bb4ba857aa956bc302336ceb802c6c06706,
which no longer seems to work.