Fix composer on PHP ≤ 7.3
Composer 2.1.6 switched PHAR signatures to SHA512 (https://github.com/composer/composer/commit/e49f24e3550329913f5eb5e92669f403c9484a91). On older versions of PHP, support for SHA-256 and SHA-512 is conditional on `hash` extension being enabled at compile time. Since we build `hash` extension in a separate package, `phar` extension assumes it will not be available and comments out the code paths, causing the following error:

	Fatal error: Uncaught PharException: phar "/nix/store/rf48l2wpxqi3vfadf3vf1z3pq35p7d5i-php-composer-2.1.6/libexec/composer/composer.phar" has a unsupported signature in /nix/store/rf48l2wpxqi3vfadf3vf1z3pq35p7d5i-php-composer-2.1.6/libexec/composer/composer.phar:23
	Stack trace:
	#0 /nix/store/rf48l2wpxqi3vfadf3vf1z3pq35p7d5i-php-composer-2.1.6/libexec/composer/composer.phar(23): Phar::mapPhar('composer.phar')
	#1 {main}
	  thrown in /nix/store/rf48l2wpxqi3vfadf3vf1z3pq35p7d5i-php-composer-2.1.6/libexec/composer/composer.phar on line 23

PHP ≥ 7.4 always bundles the `hash` extension (https://github.com/php/php-src/commit/033cafacbd8b184260c91a74ea7956b302857706) so it is not affected.

Unfortunately, making the build system aware that we are building `hash` as a shared module is not enough:

	checking for phar openssl support... configure: WARNING: Phar: sha256/sha512 signature support disabled if ext/hash is built shared
	no
	configure: error:
	You've configured extension phar to build statically, but it
	depends on extension hash, which you've configured to build shared.
	You either need to build phar shared or build hash statically for the
	build to be successful.

So we either need to build phar dynamically as well, or build hash statically. For simplicity and parity with later PHP versions, I chose the latter.