php{56,7[01]}.extensions.intl: Fix zend_sprintf linkage
After update to Clang 21, the extension would fail to build with:

    main/php_config.h:2574:5: error: declaration of 'zend_sprintf' has a different language linkage

Apparently, the header was included a second time outside the `extern "C"` block.