php56.extensions.mbstring: Fix build with Clang 21
`-Wno-implicit-function-declaration` suddenly stopped working, resulting in:

    error: use of undeclared identifier 'mbfl_filt_put_invalid_char'

Let’s apply the two upstream fixes from
https://github.com/php/php-src/commit/f809f2811964f216018f2ff7623d779991854252
which will allow us to drop both compile flags, even the one for missing
referencing of `mbfl_encoding_2022jp_kddi_aliases`:

    error: initialization of 'const char * (*)[]' from incompatible pointer type 'const char **' [-Wincompatible-pointer-types]