php{56,70,71,72,73}.extensions.mbstring: Fix build with gcc 15
In preparation for Nixpkgs bump.

PHP < 7.4 had been vendoring oniguruma:

- PHP 7.3 had 6.9.4
- PHP 7.2 had 6.3.0
- PHP 7.1 and 7.0 had 5.9.6
- PHP 5.6 had 5.9.5

Those versions no longer compile with gcc 15:

    /build/php-7.0.33/ext/mbstring/oniguruma/regparse.c:466:24: error: passing argument 2 of 'onig_st_foreach' from incompatible pointer type [-Wincompatible-pointer-types]
      466 |     onig_st_foreach(t, i_free_name_entry, 0);

    /build/php-7.1.33/ext/mbstring/oniguruma/st.c:490:23: error: too many arguments to function 'func'; expected 0, have 3
      490 |             retval = (*func)(ptr->key, ptr->record, arg);

    /build/php-7.1.33/ext/mbstring/oniguruma/st.c:490:23: error: too many arguments to function 'func'; expected 0, have 3
      490 |             retval = (*func)(ptr->key, ptr->record, arg);

    /build/php-7.1.33/ext/mbstring/oniguruma/st.c:57:40: error: too many arguments to function 'table->type->compare'; expected 0, have 2
       57 | #define EQUAL(table,x,y) ((x)==(y) || (*table->type->compare)((x),(y)) == 0)

This was fixed in 6.9.9:

https://github.com/kkos/oniguruma/releases/tag/v6.9.9

Because backporting the specific patches was a pain, I am replacing the vendored version with the latest one.

For PHP ≤ 7.1, I also had to patch the `config.m4` to handle the directory layout from oniguruma 6.