php7[0123]: Trim redundant compile flag range
The fix was introduced in ce540bb4ba857aa956bc302336ceb802c6c06706 for PHP 5.6
and then got extended for PHP ≤ 7.3 in ce540bb4ba857aa956bc302336ceb802c6c06706
but the same commit also bumped oniguruma, which made the fix redundant.

It is still needed for PHP 5.6 because of missing ref of `mbfl_encoding_2022jp_kddi_aliases`:

    error: initialization of 'const char * (*)[]' from incompatible pointer type 'const char **' [-Wincompatible-pointer-types]

Which was fixed in PHP 7.0:

https://github.com/php/php-src/commit/f809f2811964f216018f2ff7623d779991854252

and will be applied in the next commit.