php{56,7[0123]}: Fix readdir_r with clang 21
For some reason readdir_r changed number of arguments:

    error: too few arguments to function call, expected 3, have 2

Let’s replace it with `readdir` by backporting
https://github.com/php/php-src/commit/2b28f7189144a21e753dbc09efadd571121a82b9

Also requires a formatting commit to make that patch apply.

The patch is also needed for `session` extension, let’s inherit it there.
(Ideally PHP patches would be applied upstream for all built-in extensions.)