Downgrade composer on PHP ≤ 7.3
Composer 2.1.6 switched PHAR signatures to SHA512 (https://github.com/composer/composer/commit/e49f24e3550329913f5eb5e92669f403c9484a91). On older versions of PHP, support for SHA-256 and SHA-512 is conditional on `hash` extension being enabled at compile time. Since we build `hash` extension in a separate package, `phar` extension assumes it will not be available and comments out the code paths, causing the following error:

        Fatal error: Uncaught PharException: phar "/nix/store/rf48l2wpxqi3vfadf3vf1z3pq35p7d5i-php-composer-2.1.6/libexec/composer/composer.phar" has a unsupported signature in /nix/store/rf48l2wpxqi3vfadf3vf1z3pq35p7d5i-php-composer-2.1.6/libexec/composer/composer.phar:23
        Stack trace:
        #0 /nix/store/rf48l2wpxqi3vfadf3vf1z3pq35p7d5i-php-composer-2.1.6/libexec/composer/composer.phar(23): Phar::mapPhar('composer.phar')
        #1 {main}
          thrown in /nix/store/rf48l2wpxqi3vfadf3vf1z3pq35p7d5i-php-composer-2.1.6/libexec/composer/composer.phar on line 23

PHP ≥ 7.4 always bundles the `hash` extension (https://github.com/php/php-src/commit/033cafacbd8b184260c91a74ea7956b302857706) so it is not affected.

Unfortunately, it is non-trivial to fix that so for now, let’s downgrade composer on affected PHP versions.