php{56,70}: Make headers compatible with C++ extensions on Clang 21
The intl extension is written in C++, which does not like when PHP headers include the `register` keyword:

    error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]

Let’s cherry-pick a patch that removes it:
https://github.com/php/php-src/commit/af66ad28571fc3d55c33bd3b301a5508192bcdac